### ISSUE TITLE
Function for checking if the body contains a set of required values.

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#27]
Remove the need for `if 'name' in _body and 'bithday' in _body and 'email' in _body` and so on with a simple expression like this: 
```python
@post('/user'):
  required = ['name', 'birthday', 'email']

  if require_keys(required, _body):
    print(...)
    ...
```

This can be built in a similar way as `deep()` and `quick_set()` are built.

**Comment by amroakmal** [comment]
@Buscedv 
Can you assign this to me?

**Comment by Buscedv** [comment]
> @Buscedv 
> Can you assign this to me?

Sure thing!

**Comment by amroakmal** [comment]
@Buscedv 
Thanks so much!
I'm still new to open source contribution, so please pardon my question if it's naive.
Is there any sort of deadline where I need to finish the feature/solve the issue before?
I'm just asking because I'm still having some exams in college.

Thanks in advance for your understanding.

**Comment by Buscedv** [comment]
> @Buscedv
> Thanks so much!
> I'm still new to open source contribution, so please pardon my question if it's naive.
> Is there any sort of deadline where I need to finish the feature/solve the issue before?
> I'm just asking because I'm still having some exams in college.
> 
> Thanks in advance for your understanding.

Okay, no problem. No, there isn't any deadlines just let me know if you don't have time to build this or you get stuck, just so that I or someone else can take over the task.

Also, don't hesitate to ask questions if something is unclear.

Good luck!

**Comment by 0x0elliot** [comment]
i am a little intrigued but confused. would you mind giving me the specifics of this issue as well and assigning me to it as well?

**Comment by Buscedv** [comment]
> i am a little intrigued but confused. would you mind giving me the specifics of this issue as well and assigning me to it as well?

This issue is already assigned to someone else

**Comment by 0x0elliot** [comment]
no worries! i just wanted to contribute as much as i can to the project. apologies for any inconveniences due to my inexperience.

**Comment by Buscedv** [comment]
@amroakmal are you still interested?

**Comment by amroakmal** [comment]
> @amroakmal are you still interested?

Hello @Buscedv 
Yes, I'm.
I'll need approximately a week to finish all my deadlines and submissions regarding college and stuff.
I know I took too much time, so - with all apologies- if anyone else is free in this moment and wants to take it, so sure, let him/her go for that, and maybe I will contribute to another issue or by another way, the most important thing is that the project gets completed and we work on it.

I'm really so sorry for that, but those deadlines I have are not that easy, they must be completed .. you know.
Thanks for your great understanding, patience and consideration.

**Comment by Buscedv** [comment]
> > @amroakmal are you still interested?
> 
> Hello @Buscedv
> Yes, I'm.
> I'll need approximately a week to finish all my deadlines and submissions regarding college and stuff.
> I know I took too much time, so - with all apologies- if anyone else is free in this moment and wants to take it, so sure, let him/her go for that, and maybe I will contribute to another issue or by another way, the most important thing is that the project gets completed and we work on it.
> 
> I'm really so sorry for that, but those deadlines I have are not that easy, they must be completed .. you know.
> Thanks for your great understanding, patience and consideration.

No worries. You can still "keep" this issue. I think it's more important to have multiple people contribute than to push this specific feture right now, so no pressure.

**Comment by amroakmal** [comment]
Hello
I started working on the issue.
I did all the necessary initial setup to be able to contribute.
1- Right now I've a technical question, I can't find examples for the ``deep()`` and ``quick_set()`` that you mentioned.
2-And at reading the instructions you wrote, I found out the whole work will be in ask.py file, correct?
3-So, this means I should handle this post request in the ask.fm file, correct?
Is so, I can't find the code that needs to be replaced with the new one that I'll be making.

Thanks so much in advance.

**Comment by Buscedv** [comment]
> Hello
> I started working on the issue.
> I did all the necessary initial setup to be able to contribute.
> 1- Right now I've a technical question, I can't find examples for the `deep()` and `quick_set()` that you mentioned.
> 2-And at reading the instructions you wrote, I found out the whole work will be in ask.py file, correct?
> 3-So, this means I should handle this post request in the ask.fm file, correct?
> Is so, I can't find the code that needs to be replaced with the new one that I'll be making.
> 
> Thanks so much in advance.

Awesome that you started working on this feature!

You can find `deep()` and `quick_set()` on line: 943 and 951 in the `set_boilerplate()` function. You can add the new _require() function after these. Note: you're not replacing an existing function, you're adding a new one.

## Examplantion of the `set_boilerplate()` function:
This function basically adds all sorts of utility and helper functions to the output `app.py` file. Basically the point of Ask is that you shouldn't need any files/scripts (like ask.py) in your published app. The `app.py` file should be able to run completely by itself. This means that function like the `_require()` function you are creating needs to be added/inserted in to `app.py`. 

## The `_require()` function you are creating:
This is supposed to be a pretty simple function (under 10 lines). It should take in two parameters the body and a list of what parameters to look for.

Let me know if you have any questions
