### ISSUE TITLE
Make Ask work as a terminal/command line tool/app

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#34]
You should be able to use Ask without running `$ python3 ask.py [myfile].ask`, you should be able to run: `$ ask [myfile].ask`. This could be done with e.g. PyInstaller or something similar.

Related to #66

**Comment by RyanKimbrell** [comment]
I can build a macOS-10.15 exectuable using pyinstaller (python 3.8 in this venv) if you would like. I believe pyinstaller can only build the executables for the OS it is operating on.

**Comment by Buscedv** [comment]
> I can build a macOS-10.15 exectuable using pyinstaller (python 3.8 in this venv) if you would like. I believe pyinstaller can only build the executables for the OS it is operating on.


Okay I see, maybe it would actually be more user friendly to make Ask pip-installable? That would also help with verifying what you are running, executables can be a bit sketchy if you know what I mean...
