### ISSUE TITLE
Make it possible to store lists in the database

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#36]
Make a built-in solution for storing lists in the database.

Do this with *tables*. Here is a working example but this needs to get implemented into Ask as a built-in behind the scenes feature.

```python
db_class GenericList:
	id = _db.col(_db.int, _db.pk)

	def set_list(self, entry):
		if entry:
			for item in entry:
				self.push(item)

	def s(self):
		return {
			id: self.id,
			list: self.list()
		}

	def list(self):
		return [self.get(item.index) for item in GenericListItem._db.get_by(parent_id=self.id)]

	def push(self, item):
		new_item = GenericListItem(item, self.id)
		_db.add(new_item)

		return self.s()

	def get(self, index):
		item = GenericListItem._db.get_by(parent_id=self.id, index=index).first()

		return item.in_type()

	def remove(self, index):
		item = GenericListItem._db.get_by(parent_id=self.id, index=index).first()

		_db.delete(item)

db_class GenericListItem:
	id = _db.col(_db.int, _db.pk)
	index = _db.col(_db.int)
	item = _db.col(_db.bytes)
	parent_id = _db.col(_db.int)

	def _init(self, item, parent_id):
		self.item = pickle.dumps(item)
		self.parent_id = parent_id
		self.index = self.get_last_index() + 1

	def s(self):
		return {
			id: self.id,
			index: self.index,
			item: self.in_type(),
			parent_id: self.parent_id
		}

	def get_last_index(self):
		last_item = GenericListItem._db.get_by(parent_id=self.parent_id).order_by(_db.desc(GenericListItem.id)).first()

		if _db.exists(last_item):
			return last_item.index

		return -1

	def in_type(self):
		return pickle.loads(self.item)


def generic_list_factory(entry):
	generic_list = GenericList()
	_db.add(generic_list)
	generic_list.set_list(entry)

	return generic_list
```

### Usage
```python
my_list = generic_list_factory([1, 2, 3, 4])
print(my_list).list() # [1, 2, 3, 4]

my_list.push(5)
print(my_list).list() # [1, 2, 3, 4, 5]

my_list.remove(4)
print(my_list).list() # [1, 2, 3, 4]

print(my_list.get(0)) # 1
```

### How it should work when it's built-in to Ask
```python
my_list = _db.list([1, 2, 3, 4]) # or a single function e.g. my_list = make_list([1, 2, 3, 4])
my_list.push(5)
my_list.remove(4)
my_list.get(0)
my_list.list()
```

Another thought is that maybe we should add an alias for the `_db.int` type e.g. `_db.list_id` just for readabilities sake.

**Comment by hkjain** [comment]
Hey @Buscedv , it seems interesting to solve this particular problem, please explain me with the details of the same.

**Comment by Buscedv** [comment]
> Hey @Buscedv , it seems interesting to solve this particular problem, please explain me with the details of the same.

Okay awesome! Hang tight, I'll update the description with some more details in a few minutes.

**Comment by Buscedv** [comment]
Basically, We need to add a new data type for the database columns (sqlalchemy). Currently, I have "solved" this issue in a quite hacky way in my own projects:

- I create a database column with the data type of string `_db.col(_db.str)`.
- I then store comma-separated values like this: `"1,2,3,4"`, on which I then use the `split()` function to turn into a list. Like so:

```python
list = "1,2,3,4".split(",")
# This turns it into: [1, 2, 3, 4]
```

But it's a lot of unnecessary work and a big part of the philosophy behind Ask is to make common tasks as easy as possible.

One way to solve this could be to somehow automatically do the splitting of the string behind the scenes, pickleType might also work? 🤔

Let me know if you have any questions and if something in the source code is confusing 😉


Good luck and thanks for showing interest!

**Comment by hkjain** [comment]
I am not getting on where to find this problem in the source code and look into, in order to understand this.

**Comment by Buscedv** [comment]
> I am not getting on where to find this problem in the source code and look into, in order to understand this.

So **are you** or are you **not** interested in solving this? If you are I can assign this issue to you

**Comment by hkjain** [comment]
I am interested but i am not getting how to begin with, in order to resolve the problem.

**Comment by Buscedv** [comment]
> I am interested but I am not getting how to begin with, in order to resolve the problem.

Okay, basically the project uses sqlalchemy which doesn't have a list data type per-say. We need to figure out how to either:
- Use some feature that sqlalchemy offers, e.g. pickleType.
- Treat a string as a list behind the scenes.

I'll share some example code where you can see in more practical terms what the problem is.

**Comment by Buscedv** [comment]
Here is an example Ask app that shows have you have to treat listst right now:

### How you have to do it right now (the hacky way).
```python
db_class List:
	id = _db.col(_db.int, _db.pk)
	list = _db.col(_db.str)

	def _init(self, list):
		self.list = ','.join(str(item) for item in list)

	def s(self):
		return {
			id: self.id,
			list: self.list.split(',')
		}

@get('/lists'):
	lists = List._db.all()
	respond(serialize(lists))

@get('/list/<id>'):
	respond(List._db.get(id).s())

@put('/list/<id>/append'):
	list = List._db.get(id)

	if 'item' not in _body:
		respond('Missing: item', 400)

	tmp_list = list.s()['list']
	tmp_list.append(_body['item'])
	list.list = ','.join(str(item) for item in tmp_list)

	_db.save()

	respond(list.s())

@post('/list'):
	data = ''

	if 'list' in _body:
		data = _body['list']

	list = List(data)
	_db.add(list)

	respond(list.s())

```

This is definitely not optimal, some problems with this include:
- Lots of code needed.
- The original data type(s) for the list elements are lost.
- Doesn't support all forms and types of data.

### What It should look like (what I want)

```python
db_class List:
	id = _db.col(_db.int, _db.pk)
	list = _db.col(_db.list)

	def _init(self, list):
		self.list = list

	def s(self):
		return {
			id: self.id,
			list: self.list
		}

@get('/lists'):
	lists = List._db.all()
	respond(serialize(lists))

@get('/list/<id>'):
	respond(List._db.get(id).s())

@put('/list/<id>/append'):
	list = List._db.get(id)

	if 'item' not in _body:
		respond('Missing: item', 400)

	list.list.append(_body['item'])

	_db.save()

	respond(list.s())

@post('/list'):
	data = ''

	if 'list' in _body:
		data = _body['list']

	list = List(data)
	_db.add(list)

	respond(list.s())

```

**Comment by Buscedv** [comment]
Using `json.loads` and `json.dumps` might also be a good solution.

**Comment by Buscedv** [comment]
Actually, this might be too complex for a newcomer to the project, I greatly misjudged the complexity of this problem... You can of course help if you want but I completely understand if this is too confusing. Just let me know if you want to drop this and do something else instead (there are other issues ex. #33)

**Comment by just-code-it-anyway** [comment]
Ya, its getting a bit complex for me. At the very beginning even i thought of the same idea of storing it as a string, but after knowing the loopholes in it i gave it up. 
Instead of bothering you i would like to look onto new issues on this repo.

**Comment by Buscedv** [comment]
> Ya, its getting a bit complex for me. At the very beginning even i thought of the same idea of storing it as a string, but after knowing the loopholes in it i gave it up. 
> 
> Instead of bothering you i would like to look onto new issues on this repo.

No problem.
