### ISSUE TITLE
Add random number generating functions

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#37]
Add a new module called `_random`. It should work like `_hash` and `_env` do (they get added in as boilerplate code on lines *514*-*662* in `ask.py`). Behind the scenes, this should use Pythons own built-in `random` library.

**It should have the following functions:**
```python
# Single items
_random.int(0, 8) # Returns a random integer between 0 and 8.
_random.float(1.5, 3.8) # Returns a random float between 1.5 and 3.8.
_random.item(['a', 'b', 'c']) # Returns a random element from the passed in list.

# Multiple items
_random.ints(0, 8, 3) # Returns 3 random integers between 0 and 8 in a list.
_random.floats(1.5, 3.8, 8) # Returns 8 random floats between 1.5 and 3.8.
_random.items(['a', 'b', 'c'], 4) # Returns 4 random elements from the passed in list.

# You can add more functions if you want but at least these ones as a start...
```

**Helpful links**
- https://docs.python.org/3/library/random.html
- https://www.w3schools.com/python/module_random.asp

**Comment by Buscedv** [comment]
@just-code-it-anyway are you interested?

**Comment by just-code-it-anyway** [comment]
> @just-code-it-anyway are you interested?

Yes surely i would like to.😀

**Comment by just-code-it-anyway** [comment]
@Buscedv Please have a look over the PR #38

**Comment by just-code-it-anyway** [comment]
@Buscedv , i've made the requested changes. #38 , please refer the 2nd commit.
