### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#45]
We need unit tests!

## Specs
- Preferably use Pythons built-in `unittest` framework.
- The tests should be in a script called: `test_ask.py`
- The most important methods to test are (in no particular order):
  - `get_root_from_file_path()`
  - `route_path_to_func_name()`
  - `maybe_place_space_before()`
  - `route_params()`
  - `get_current_tab_level()`
  - `parser()` ❗️
  - `lex_var_keyword()`
  - `add_part()`
  - `fix_up_code_line()`
  - `lexer()` ❗️
 
(❗️= complicated tests required)

**Comment by pillemer** [comment]
Hi, I'd love to help on this issue if I can. I'm fairly new so can you give me a little more direction on how to go about creating unit tests for this?

**Comment by Buscedv** [comment]
> Hi, I'd love to help on this issue if I can. I'm fairly new so can you give me a little more direction on how to go about creating unit tests for this?

Awesome! Have you done python testing before?

**Comment by pillemer** [comment]
I've done it as part of a couple of courses I've taken but not on my own from scratch. If you could give me an example or two of what exactly you want I can continue from there.

**Comment by Buscedv** [comment]
> I've done it as part of a couple of courses I've taken but not on my own from scratch. If you could give me an example or two of what exactly you want I can continue from there.

Okay sounds good! I'll make a few test and then you'll continue from there. If you want to read up on it I'll be using Python's built-in testing framework: "unittest" to write the tests.

**Comment by pillemer** [comment]
That's perfect. Thank you. I will do some research in preparation.

**Comment by Buscedv** [comment]
@pillemer I've now created two unit tests to get you started. They are in a new file called test_ask.py, just add all tests you create there. Don't hesitate to ask questions (just keep in mind our 8-hour timezone difference 😉). Good luck!

**Comment by pillemer** [comment]
I've gone ahead and created a test for maybe_place_space_before and created a draft pull request. 
Please let me know if anything needs work, is wrong, etc. This is all new to me and I'm eager to learn. (code-wise, style-wise and git-wise)
