### ISSUE TITLE
Toggle Flask debug mode

### ISSUE THREAD

**Issue by Buscedv** [Buscedv/Ask#56]
Right now by default the automatically started server (`flask run`) has flask's debug mode off. It should be turned on when Ask is run with the DEV flag `-d`.  This can be achieved with environment variables. More specifically the `FLASK_ENV` variable. Read more: https://flask.palletsprojects.com/en/1.1.x/cli/#environments

**Comment by 0x0elliot** [comment]
can you assign this issue to me?

**Comment by 0x0elliot** [comment]
i am a little unsure as to where i need to add things. will be kind of you to guide me in the right direction.

**Comment by Buscedv** [comment]
> i am a little unsure as to where i need to add things. will be kind of you to guide me in the right direction.

Awesome to gave you on the project! Okay, basically there is a global variable (boolean) called `is_dev` (in ask.py). Right before `flask run` we need to export an environment variable (check the link refereced in the issue description) if `is_dev` is true.

**Comment by 0x0elliot** [comment]
thanks! i will work on it. thank you so much for being kind enough to let me try. i will start working on it as soon as possible.

**Comment by 0x0elliot** [comment]
i have made a pull request. kindly review the branch and let me know if i missed something. thank you.
